name: Run tests

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v4

      - run: |
          cd 1 # TODO
          uv run sync
          uv run pytest
